name: Spring boot CI

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - lab_3

jobs:
  check-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Grant scripts permition
        run: chmod +x ./mvnw ./.test/run-test.sh

      - name: Compile Spring app
        run: ./mvnw clean package -DskipTests

      - name: Run Spring app
        run: |
          java -jar ./target/*.jar &
          sleep 15 # Даем Spring Boot время запуститься перед тестами

      - name: Run tests
        run: ./.test/run-test.sh